language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - pip install bikeshed
  - bikeshed update
  - pip install Pygments
 
script:
  - bash ./scripts/deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "6c9ad971e3e1"
  
